"use client";

import { ArrowLeft, Building2, CalendarDays, CreditCard, FileText } from "lucide-react";
import { useRouter } from "next/navigation";
import { formatRupiah, getTaxpayer, mockConfig, type SptpdPeriodRecord } from "@/lib/mock-data";

export function SptpdDetail({ record, onBack }: { record: SptpdPeriodRecord; onBack: () => void }) {
  const router = useRouter();
  const taxpayer = getTaxpayer(record.taxpayerId);
  if (!taxpayer) return null;
  const difference = record.mposAmount - record.reportedAmount;
  const statusClass = record.status === "Sudah Dilaporkan" ? "is-reported" : record.status === "Perlu Ditinjau" ? "is-review" : "is-missing";
  const reportDate = record.status === "Belum Dilaporkan" ? "Belum dilaporkan" : `20 ${record.period} ${record.year}`;
  const reference = `SPTPD/PBJT/${record.year}/${String(record.monthIndex + 25).padStart(4, "0")}`;
  return <div className="sptpd-detail-view"><button className="taxpayer-back" onClick={onBack}><ArrowLeft size={17} />Kembali</button><section className="sptpd-detail-hero"><header><div><p><FileText size={16} />SPTPD</p><h1>{reference}</h1><strong>{taxpayer.name}</strong><span>P.{taxpayer.id.replace("wp-", "")}.001</span></div><span className={`sptpd-status ${statusClass}`}><i />{record.status}</span></header><div className="sptpd-detail-meta"><div><span>Masa Pajak</span><strong>{record.period} {record.year}</strong></div><div><span>Tanggal Lapor</span><strong>{reportDate}</strong></div><div><span>Jenis Usaha</span><strong>{taxpayer.type}</strong></div><div><span>Kecamatan</span><strong>{taxpayer.district}</strong></div></div></section><div className="sptpd-detail-grid"><section className="sptpd-value-card"><h2>Nilai Pelaporan</h2><dl><div><dt>Omzet Dilaporkan</dt><dd>{formatRupiah(record.reportedAmount)}</dd></div><div><dt>Dasar Pengenaan</dt><dd>{formatRupiah(record.reportedAmount)}</dd></div><div><dt>Tarif PBJT</dt><dd>{mockConfig.pbjtRate * 100}%</dd></div><div className="sptpd-total-row"><dt>PBJT Dilaporkan</dt><dd>{formatRupiah(record.pbjtAmount)}</dd></div></dl></section><section className="sptpd-reconciliation-card"><h2>Rekonsiliasi MPOS vs SPTPD</h2><div className="sptpd-reconciliation-values"><div><span>Data MPOS</span><strong>{formatRupiah(record.mposAmount)}</strong></div><b>→</b><div><span>Data SPTPD</span><strong>{formatRupiah(record.reportedAmount)}</strong></div></div><div className={`sptpd-difference ${difference > 0 ? "has-difference" : "no-difference"}`}><span>Selisih Omzet</span><strong>{formatRupiah(difference)}</strong></div><p>Selisih merupakan indikasi untuk ditinjau, bukan otomatis berarti pelanggaran.</p></section></div><section className="sptpd-payment-card"><h2>Pembayaran Terkait</h2><div className="sptpd-payment-table"><div><span>REFERENSI</span><span>DIBAYAR</span><span>TANGGAL</span><span>METODE</span><span>STATUS</span></div><div><code>REF-{record.year}{String(record.monthIndex + 25).padStart(4, "0")}</code><strong>{formatRupiah(record.pbjtAmount)}</strong><span>{reportDate}</span><span><CreditCard size={15} />Tunai</span><span className="sptpd-status is-reported"><i />{record.status === "Belum Dilaporkan" ? "Belum Lunas" : "Lunas"}</span></div></div></section><div className="sptpd-detail-actions"><button className="primary-action" onClick={() => router.push("/dashboard#reconciliation")}>Lihat Rekonsiliasi</button><button className="secondary-action"><Building2 size={16} />Lihat WP</button><button className="secondary-action" onClick={() => window.open(`/dashboard/sptpd/${record.id}/print`, "_blank", "noopener,noreferrer")}><CalendarDays size={16} />Cetak SPTPD</button></div></div>;
}

export function SptpdPrintView({ record }: { record: SptpdPeriodRecord }) {
  const taxpayer = getTaxpayer(record.taxpayerId);
  if (!taxpayer) return null;
  const title = taxpayer.type === "Hotel" ? "PBJT - JASA PERHOTELAN" : "PBJT - JASA MAKANAN DAN/ATAU MINUMAN";
  return <main className="sptpd-print-page"><section className="sptpd-print-form"><header><strong>PEMERINTAH KABUPATEN KEPULAUAN MENTAWAI</strong><span>TUAPEJAT - SIPORA</span><small>Surat Pemberitahuan Pajak Daerah</small><h1>SPTPD</h1><h2>{title}</h2><p>Masa Pajak: <b>{record.period} {record.year}</b></p></header><div className="sptpd-print-section"><h3>I. IDENTITAS WAJIB PAJAK DAERAH</h3><dl><div><dt>Nama Wajib Pajak</dt><dd>{taxpayer.name}</dd></div><div><dt>NPWPD</dt><dd>P.{taxpayer.id.replace("wp-", "")}.001</dd></div><div><dt>Jenis Usaha</dt><dd>{taxpayer.type}</dd></div><div><dt>Alamat Wajib Pajak</dt><dd>Jl. Pantai Tuapejat, {taxpayer.village}, Mentawai</dd></div></dl></div><div className="sptpd-print-section"><h3>II. DATA PERPAJAKAN</h3><table><tbody><tr><td>Omzet berdasarkan data MPOS</td><td>{formatRupiah(record.mposAmount)}</td></tr><tr><td>Omzet yang dilaporkan</td><td>{formatRupiah(record.reportedAmount)}</td></tr><tr><td>Dasar Pengenaan Pajak</td><td>{formatRupiah(record.reportedAmount)}</td></tr><tr><td>Tarif PBJT</td><td>{mockConfig.pbjtRate * 100}%</td></tr><tr className="print-total"><td>PBJT yang harus dibayar</td><td>{formatRupiah(record.pbjtAmount)}</td></tr></tbody></table></div><div className="sptpd-print-signature"><div>Wajib Pajak / Penanggung Jawab<br /><br /><br />(________________________)</div><div>Tuapejat, {record.year}<br />Petugas Penerima<br /><br /><br />(________________________)</div></div></section></main>;
}
