"use client";

import { AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, Download, Search, ShieldAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { FilterDropdown } from "@/components/dashboard/filter-dropdown";
import { formatRupiah, getSptpdHistory, mockConfig, mockStpdSeeds, mockTaxpayers } from "@/lib/mock-data";

export function StpdContent() {
  const router = useRouter();
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("Semua");
  const [page, setPage] = useState(1);
  const metrics = [
    { label: "TOTAL STPD", value: String(mockStpdSeeds.length), note: "", icon: ShieldAlert, tone: "slate" },
    { label: "OUTSTANDING", value: String(mockStpdSeeds.filter((seed) => seed.paidRate < 1).length), note: `${mockStpdSeeds.filter((seed) => seed.status === "Overdue").length} overdue`, icon: AlertTriangle, tone: "amber" },
    { label: "NILAI OUTSTANDING", value: `Rp ${mockConfig.stpdOutstanding.toLocaleString("id-ID")}`, note: "Sisa tagihan", icon: ShieldAlert, tone: "red" },
    { label: "LUNAS", value: String(mockStpdSeeds.filter((seed) => seed.paidRate >= 1).length), note: "Sudah dibayar", icon: CheckCircle2, tone: "green" },
  ];
  const rows = useMemo(() => mockStpdSeeds.map((seed, index) => { const taxpayer = mockTaxpayers.find((item) => item.id === seed.taxpayerId)!; const record = getSptpdHistory(seed.taxpayerId).find((item) => item.monthIndex === seed.monthIndex)!; const principal = Math.round(record.mposAmount * mockConfig.pbjtRate); const penalty = Math.round(principal * .01); const total = principal + penalty; const paid = Math.round(total * seed.paidRate); return { ...seed, taxpayer, record, reference: `STPD/PBJT/${record.year}/${String(index + 1).padStart(4, "0")}`, principal, penalty, total, paid, remaining: total - paid, due: `04 ${record.monthIndex === 11 ? "Januari" : record.period} ${record.year + (record.monthIndex === 11 ? 1 : 0)}` }; }).filter(({ taxpayer, reference, status: rowStatus }) => (status === "Semua" || status === rowStatus) && `${reference} ${taxpayer.name}`.toLowerCase().includes(query.toLowerCase())), [query, status]);
  const pageSize = 10;
  const totalPages = Math.max(1, Math.ceil(rows.length / pageSize));
  const visibleRows = rows.slice((page - 1) * pageSize, page * pageSize);
  const exportRows = () => { const csv = ["Nomor STPD,Wajib Pajak,Masa Pajak,Pokok,Sanksi,Total,Dibayar,Sisa,Jatuh Tempo,Status", ...rows.map((row) => `${row.reference},${row.taxpayer.name},${row.record.period} ${row.record.year},${row.principal},${row.penalty},${row.total},${row.paid},${row.remaining},${row.due},${row.status}`)].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "stpd.csv"; link.click(); URL.revokeObjectURL(url); };
  const openDetail = (row: (typeof rows)[number]) => { window.sessionStorage.setItem("stpd-detail-return", "/dashboard#stpd"); router.push(`/dashboard/stpd/${row.taxpayer.id}-${row.record.year}-${row.record.monthIndex + 1}`); };

  return <div className="dashboard-content stpd-page-content"><div className="stpd-page-heading"><h1>STPD</h1><p>Surat Tagihan Pajak Daerah - monitoring tagihan dan pembayaran</p></div><div className="overview-metric-grid stpd-page-metric-grid">{metrics.map(({ label, value, note, icon: Icon, tone }) => <article className="overview-metric" key={label}><div className="overview-metric-label"><span>{label}</span><i className={`metric-icon ${tone}`}><Icon size={19} /></i></div><strong>{value}</strong>{note && <p>{note}</p>}</article>)}</div><section className="stpd-page-table-panel"><header><label className="stpd-page-search"><Search size={18} /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Cari nomor, WP..." /></label><div className="stpd-page-actions"><FilterDropdown label="Status:" value={status} options={["Semua", "Overdue", "Partial", "Outstanding"]} onChange={(value) => { setStatus(value); setPage(1); }} /><button className="stpd-page-export" onClick={exportRows}><Download size={16} />Export</button></div></header><div className="stpd-page-table-wrap"><table className="stpd-page-table"><thead><tr><th>NOMOR STPD</th><th>WAJIB PAJAK</th><th>POKOK</th><th>SANKSI</th><th>TOTAL</th><th>DIBAYAR</th><th>SISA</th><th>JATUH TEMPO</th><th>STATUS</th></tr></thead><tbody>{visibleRows.map((row) => <tr key={row.reference} tabIndex={0} role="button" onClick={() => openDetail(row)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); openDetail(row); } }}><td className="stpd-page-reference"><strong>{row.reference}</strong><small>{row.record.period} {row.record.year}</small></td><td className="stpd-page-taxpayer">{row.taxpayer.name}</td><td>{formatRupiah(row.principal)}</td><td>{formatRupiah(row.penalty)}</td><td className="stpd-page-total">{formatRupiah(row.total)}</td><td className="stpd-page-paid">{formatRupiah(row.paid)}</td><td className="stpd-page-remaining">{formatRupiah(row.remaining)}</td><td>{row.due}</td><td><span className={`stpd-list-status ${row.status.toLowerCase()}`}><i />{row.status}</span></td></tr>)}</tbody></table></div><footer className="stpd-page-footer"><span>Menampilkan {visibleRows.length ? (page - 1) * pageSize + 1 : 0}-{Math.min(page * pageSize, rows.length)} dari {rows.length} data</span><div className="pagination"><button aria-label="Halaman sebelumnya" disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}><ChevronLeft size={16} /></button><span>{page}</span><button aria-label="Halaman berikutnya" disabled={page >= totalPages} onClick={() => setPage((value) => Math.min(totalPages, value + 1))}><ChevronRight size={16} /></button></div></footer></section></div>;
}
